# Generated by Django 4.1.2 on 2022-11-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('requirement', models.TextField()),
                ('experience', models.CharField(max_length=250)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'ordering': ('-date_posted',),
            },
        ),
    ]
